#!/bin/sh

for host in hadoop101 hadoop102 hadoop103
do
    echo ======================= $host =============================
    ssh $host "source /etc/profile;/opt/module/jdk1.8.0_144/bin/jps" | grep -v Jps
done
